# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db548e0590f6a8b66bdb7f2b3ce05247e0f1df4cab646feb6f141d219ceee70863983a66668a6e84a5cd5e4e7809bae05eba4e914bfcf1faaf73ea65d258186e

test:
  secret_key_base: 8443cdb327ef06456ffe0ee36ca7a15142f5c1f75e41ca1493db25805bc01e556b16cce249de56fae50b8b36c814820bc1862e39fe96e4cd80290e36ac05f30c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
